"""add Department

Revision ID: 42471f14900d
Revises: 5eb2d3ed6f48
Create Date: 2025-01-15 21:12:14.376852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42471f14900d'
down_revision = '5eb2d3ed6f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
