"""rename address

Revision ID: 512b6e691711
Revises: c6affd85eb4d
Create Date: 2025-01-15 21:29:47.303318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512b6e691711'
down_revision = 'c6affd85eb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
